{
 "title": "GitHub",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Tracee", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_repo_stars{repo=\"tracee\"}"
    }
   ]
  },
  {
   "title": "Number of forks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_repo_forks{repo=\"tracee\"}"
    }
   ]
  },
  {
   "title": "Release Downloads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_release_downloads{repo=\"tracee\"})"
    }
   ]
  },
  { "title": "Trivy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Number of forks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_repo_forks{repo=\"trivy\"}"
    }
   ]
  },
  {
   "title": "Number of stars",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_repo_stars{repo=\"trivy\"}"
    }
   ]
  },
  {
   "title": "Release Downloads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(github_repo_release_downloads{repo=\"trivy\"})"
    }
   ]
  }
 ]
}