{
 "title": "GitHub",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "100 Days of Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Repo Stars",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_repo_stars{repo=\"100DaysOfKubernetes\"}"
    }
   ]
  },
  {
   "title": "Number of forks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "github_repo_forks{repo=\"100DaysOfKubernetes\"}"
    }
   ]
  },
  {
   "title": "Trivy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of forks",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "github_repo_forks{repo=\"trivy\"}"
      }
     ]
    },
    {
     "title": "Number of stars",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "github_repo_stars{repo=\"trivy\"}"
      }
     ]
    },
    {
     "title": "Release Downloads",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(github_repo_release_downloads{repo=\"trivy\"})"
      }
     ]
    }
   ]
  }
 ]
}